[package]
name = "lifeline-client"
version = "0.1.0"
authors = ["Simon Engledew <simon.engledew@gmail.com>"]

[dependencies]
libc = "0.2"
getopts = "0.2"

[profile.release]
lto = true
panic = 'abort'
